suggested: false
tech-preview: false
environments:
  - Stage
stages:
  - name: Build Release
    description: creates a new version then builds and deploys the project into the maven repository 
  - name: Rollout to Stage
    description: stages the new version into the Stage environment 
 